# Generated by Django 4.2.1 on 2023-08-12 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0012_product_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='count_star',
            field=models.IntegerField(default=1, verbose_name='Количество звёзд'),
            preserve_default=False,
        ),
    ]
