# Generated by Django 4.2.1 on 2023-08-12 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0013_comment_count_star'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='nickname',
        ),
    ]
