# Generated by Django 4.2.1 on 2023-08-12 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0014_remove_comment_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pre_order',
            field=models.BooleanField(default=False, verbose_name='Предзаказ'),
        ),
    ]
